server:
  port: 8080
spring:
  application:
    name: 'user'
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        
        jdbc:
          lob:
            non_contextual_creation: true

            