spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/apirest
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

            
contato:
  disco:
    diretorio-fotos: fotos
    raiz: /tmp/contato-disco
            